title: Health Companion App - UX/UI Blog Post
description: A UX/UI design process on mobile design that can improve medication adherence, healthcare communication, and chronic condition management.
google_analytics:
theme: jekyll-theme-cayman
